# Generated by Django 5.2.3 on 2025-07-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
