# Generated by Django 5.2.3 on 2025-09-12 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('garment_type', models.CharField(choices=[('dress', 'Dress'), ('pants', 'Pants/Trousers'), ('skirt', 'Skirt'), ('blouse', 'Blouse/Shirt'), ('jacket', 'Jacket/Blazer'), ('jeans', 'Jeans'), ('formal', 'Formal Wear'), ('other', 'Other')], max_length=20, verbose_name='Garment Type')),
                ('alteration_type', models.CharField(help_text='Comma-separated list of alteration types', max_length=200, verbose_name='Alteration Types')),
                ('measurements', models.TextField(blank=True, help_text='Optional measurements or sizing notes', null=True, verbose_name='Measurements')),
                ('description', models.TextField(blank=True, help_text='Any additional details or special requests', null=True, verbose_name='Special Instructions')),
                ('delivery_option', models.CharField(choices=[('pickup', 'Pickup from Location'), ('delivery', 'Home Delivery')], default='pickup', max_length=20, verbose_name='Delivery Option')),
                ('pickup_address', models.TextField(blank=True, help_text='Address for garment pickup (if applicable)', null=True, verbose_name='Pickup Address')),
                ('delivery_address', models.TextField(blank=True, help_text='Address for garment delivery (if applicable)', null=True, verbose_name='Delivery Address')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('issue_description', models.TextField(blank=True, help_text='Brief description of what needs to be altered', null=True, verbose_name='Issue Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Alteration Request',
                'verbose_name_plural': 'Alteration Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlterationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alteration_images/%Y/%m/%d/', verbose_name='Garment Image')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Image Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alteration_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='alteration.alterationrequest')),
            ],
            options={
                'verbose_name': 'Alteration Image',
                'verbose_name_plural': 'Alteration Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
